### ISSUE TITLE
Navigating with arrow keys affects all carousels, not just the carousel in focus

### ISSUE THREAD

**Issue by cewen** [glidejs/glide#262]
I'm creating a few Glide sliders on the page like so:

    import Glide from '@glidejs/glide';
    
    const sliders = document.querySelectorAll('.glide');
    
    sliders.forEach((slider) => {
      new Glide(slider).mount();
    });

The sliders all work perfectly well independently, but when I try to focus on one and navigate with the keyboard, all of the sliders are affected and change to either the next or previous slide.

Pressing the arrow keys should only affect the slider that the user is focused into.

From inspecting the source code it looks like this may be because Glide is attaching a `keyup` listener on the `document` element, rather on each individual `.glide` element.

**Comment by cylott** [comment]
I'd also love to know a fix for this one!

**Comment by shane-sigma** [comment]
```
import Glide from '@glidejs/glide';

const sliders = document.querySelectorAll('.glide');

let sliderObj = {};

sliders.forEach((slider, i) => {
    // Add glide to the object for reference
    sliderObj[i] = new Glide(slider);
    // Attatch event listener and instruct slide to go left and right
    slider.addEventListener('keyup', (e) => {
        if (e.keyCode == 39) this.sliderObj[i].go('>');
        if (e.keyCode == 37) this.sliderObj[i].go('<');
    });
    // Mount
    sliderObj[i].mount();
});
```

**Comment by cylott** [comment]
> Disable keyboard events globally for Glide and then attach specific events when you mount the individual sliders.
> 
> ```
> import Glide from '@glidejs/glide';
> 
> const sliders = document.querySelectorAll('.glide');
> 
> let sliderObj = {};
> 
> sliders.forEach((slider, i) => {
>     // Add glide to the object for reference, disable global keyboard
>     sliderObj[i] = new Glide(slider, {
>         type: 'carousel',
>         keyboard: false
>     });
>     // Attatch event listener and instruct slide to go left and right
>     slider.addEventListener('keyup', (e) => {
>         if (e.keyCode == 39) this.sliderObj[i].go('>');
>         if (e.keyCode == 37) this.sliderObj[i].go('<');
>     });
>     // Mount
>     sliderObj[i].mount();
> });
> ```

Hi there, thanks for this code! I have a page with 6 glidejs sliders on the same page. I'm not sure if this is what the OP means, but I would like the keyboard to control only the slider that the mouse is hovering over. Implementing this code does not accomplish this for me.

**Comment by poveu** [comment]
However this is still a workaround, not a fix.

**Comment by cylott** [comment]
> However this is still a workaround, not a fix.

A good workaround

**Comment by poveu** [comment]
> > However this is still a workaround, not a fix.
> 
> A good workaround

Haha I'm not saying it's not! :P
Just pointing out that this should be fixed in future releases.

**Comment by thenomadicmann** [comment]
Still having this issue in April 2021. It is conflicting with my Bootstrap 4 carousel on the same page.

**Comment by Ceyar** [comment]
Mmmh, using `keyup` eventListener will let me use keyboard. I have to click on the carousel to get he keyboard enabled.

Did someone had the same problem and fixed it?

Thanks
